### ISSUE TITLE
open format the docs

### ISSUE THREAD

**Issue by TomConlin** [Dannyzen/openresearch#1]
Including copies of your documents in open formats would help.

**Comment by auzias** [comment]
Your project is a great idea promoting good practice, but doing so in a closed format harden to reach the project goals!

**Comment by Dannyzen** [comment]
Thanks for the feedback. I'll get to changing to open formats soon.

**Comment by Dannyzen** [comment]
This change has been made. Please open a new issue if you have additional feedback.
